spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
    # System.out을 통해 로그를 남김
    #   show_sql: true
      format-sql: true

logging:
  level:
  # Logger를 통해 log를 남기는 설정
    org.hibnrnate.SQL: debug
    # 쿠ㅝ리 파라미터 출력
    org.hibernate.type: trace